export type Resultado = "1" | "X" | "2" | null;
export type Fase =
  | "grupos"
  | "1/16"
  | "octavos"
  | "cuartos"
  | "semis"
  | "3er_puesto"
  | "final";

export interface Partido {
  id: string;
  fase: Fase;
  grupo?: string;
  fechaISO: string;
  fecha: string;
  hora: string;
  sede: string;
  local: string;
  visita: string;
}

export interface Equipo {
  nombre: string;
  codigo: string;
  grupo?: string;
}

export const PUNTOS_SIGNO: Record<Fase, number> = {
  grupos: 3,
  "1/16": 5,
  octavos: 5,
  cuartos: 8,
  semis: 8,
  "3er_puesto": 10,
  final: 10,
};

export const PUNTOS_EXACTO: Record<Fase, number> = {
  grupos: 5,
  "1/16": 8,
  octavos: 8,
  cuartos: 12,
  semis: 12,
  "3er_puesto": 15,
  final: 15,
};

export type EstadoApuesta = "muy_temprano" | "abierto" | "cerrado";

export function getEstadoApuesta(partido: Partido): EstadoApuesta {
  const ahora = new Date();
  const inicio = new Date(partido.fechaISO);
  const unaHoraAntes = new Date(inicio.getTime() - 1 * 60 * 60 * 1000);
  const finGrupos = new Date("2026-06-28T23:00:00Z");

  if (partido.fase === "grupos") {
    if (ahora < unaHoraAntes) return "abierto";
    return "cerrado";
  }
  if (ahora < finGrupos) return "muy_temprano";
  if (ahora < unaHoraAntes) return "abierto";
  return "cerrado";
}

export function estaBloquado(partido: Partido): boolean {
  return getEstadoApuesta(partido) !== "abierto";
}

export function horaCierre(partido: Partido): string {
  const inicio = new Date(partido.fechaISO);
  const cierre = new Date(inicio.getTime() - 1 * 60 * 60 * 1000);
  return cierre.toLocaleTimeString("es-AR", {
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "America/Argentina/Buenos_Aires",
  });
}

export const EQUIPOS: Record<string, Equipo> = {
  México: { nombre: "México", codigo: "mx", grupo: "A" },
  Sudáfrica: { nombre: "Sudáfrica", codigo: "za", grupo: "A" },
  "Corea del Sur": { nombre: "Corea del Sur", codigo: "kr", grupo: "A" },
  "Rep. Checa": { nombre: "Rep. Checa", codigo: "cz", grupo: "A" },
  Canadá: { nombre: "Canadá", codigo: "ca", grupo: "B" },
  Bosnia: { nombre: "Bosnia", codigo: "ba", grupo: "B" },
  Qatar: { nombre: "Qatar", codigo: "qa", grupo: "B" },
  Suiza: { nombre: "Suiza", codigo: "ch", grupo: "B" },
  Brasil: { nombre: "Brasil", codigo: "br", grupo: "C" },
  Marruecos: { nombre: "Marruecos", codigo: "ma", grupo: "C" },
  Haití: { nombre: "Haití", codigo: "ht", grupo: "C" },
  Escocia: { nombre: "Escocia", codigo: "gb-sct", grupo: "C" },
  "Estados Unidos": { nombre: "Estados Unidos", codigo: "us", grupo: "D" },
  Paraguay: { nombre: "Paraguay", codigo: "py", grupo: "D" },
  Australia: { nombre: "Australia", codigo: "au", grupo: "D" },
  Turquía: { nombre: "Turquía", codigo: "tr", grupo: "D" },
  Alemania: { nombre: "Alemania", codigo: "de", grupo: "E" },
  Curazao: { nombre: "Curazao", codigo: "cw", grupo: "E" },
  "Costa de Marfil": { nombre: "Costa de Marfil", codigo: "ci", grupo: "E" },
  Ecuador: { nombre: "Ecuador", codigo: "ec", grupo: "E" },
  "Países Bajos": { nombre: "Países Bajos", codigo: "nl", grupo: "F" },
  Japón: { nombre: "Japón", codigo: "jp", grupo: "F" },
  Suecia: { nombre: "Suecia", codigo: "se", grupo: "F" },
  Túnez: { nombre: "Túnez", codigo: "tn", grupo: "F" },
  Bélgica: { nombre: "Bélgica", codigo: "be", grupo: "G" },
  Egipto: { nombre: "Egipto", codigo: "eg", grupo: "G" },
  Irán: { nombre: "Irán", codigo: "ir", grupo: "G" },
  "Nueva Zelanda": { nombre: "Nueva Zelanda", codigo: "nz", grupo: "G" },
  España: { nombre: "España", codigo: "es", grupo: "H" },
  "Cabo Verde": { nombre: "Cabo Verde", codigo: "cv", grupo: "H" },
  "Arabia Saudita": { nombre: "Arabia Saudita", codigo: "sa", grupo: "H" },
  Uruguay: { nombre: "Uruguay", codigo: "uy", grupo: "H" },
  Francia: { nombre: "Francia", codigo: "fr", grupo: "I" },
  Senegal: { nombre: "Senegal", codigo: "sn", grupo: "I" },
  Irak: { nombre: "Irak", codigo: "iq", grupo: "I" },
  Noruega: { nombre: "Noruega", codigo: "no", grupo: "I" },
  Argentina: { nombre: "Argentina", codigo: "ar", grupo: "J" },
  Argelia: { nombre: "Argelia", codigo: "dz", grupo: "J" },
  Austria: { nombre: "Austria", codigo: "at", grupo: "J" },
  Jordania: { nombre: "Jordania", codigo: "jo", grupo: "J" },
  Portugal: { nombre: "Portugal", codigo: "pt", grupo: "K" },
  "RD del Congo": { nombre: "RD del Congo", codigo: "cd", grupo: "K" },
  Uzbekistán: { nombre: "Uzbekistán", codigo: "uz", grupo: "K" },
  Colombia: { nombre: "Colombia", codigo: "co", grupo: "K" },
  Inglaterra: { nombre: "Inglaterra", codigo: "gb-eng", grupo: "L" },
  Croacia: { nombre: "Croacia", codigo: "hr", grupo: "L" },
  Ghana: { nombre: "Ghana", codigo: "gh", grupo: "L" },
  Panamá: { nombre: "Panamá", codigo: "pa", grupo: "L" },
};

export const PARTIDOS: Partido[] = [
  // ── GRUPO A ──
  {
    id: "A1",
    fase: "grupos",
    grupo: "A",
    fechaISO: "2026-06-11T19:00:00Z",
    fecha: "11 Jun",
    hora: "16:00",
    sede: "Ciudad de México",
    local: "México",
    visita: "Sudáfrica",
  },
  {
    id: "A2",
    fase: "grupos",
    grupo: "A",
    fechaISO: "2026-06-12T02:00:00Z",
    fecha: "11 Jun",
    hora: "23:00",
    sede: "Guadalajara",
    local: "Corea del Sur",
    visita: "Rep. Checa",
  },
  {
    id: "A3",
    fase: "grupos",
    grupo: "A",
    fechaISO: "2026-06-18T16:00:00Z",
    fecha: "18 Jun",
    hora: "13:00",
    sede: "Atlanta",
    local: "Rep. Checa",
    visita: "Sudáfrica",
  },
  {
    id: "A4",
    fase: "grupos",
    grupo: "A",
    fechaISO: "2026-06-19T01:00:00Z",
    fecha: "18 Jun",
    hora: "22:00",
    sede: "Guadalajara",
    local: "México",
    visita: "Corea del Sur",
  },
  {
    id: "A5",
    fase: "grupos",
    grupo: "A",
    fechaISO: "2026-06-25T01:00:00Z",
    fecha: "25 Jun",
    hora: "20:00",
    sede: "Guadalajara",
    local: "México",
    visita: "Rep. Checa",
  },
  {
    id: "A6",
    fase: "grupos",
    grupo: "A",
    fechaISO: "2026-06-25T01:00:00Z",
    fecha: "25 Jun",
    hora: "20:00",
    sede: "Ciudad de México",
    local: "Sudáfrica",
    visita: "Corea del Sur",
  },
  // ── GRUPO B ──
  {
    id: "B1",
    fase: "grupos",
    grupo: "B",
    fechaISO: "2026-06-12T19:00:00Z",
    fecha: "12 Jun",
    hora: "16:00",
    sede: "Toronto",
    local: "Canadá",
    visita: "Bosnia",
  },
  {
    id: "B2",
    fase: "grupos",
    grupo: "B",
    fechaISO: "2026-06-13T19:00:00Z",
    fecha: "13 Jun",
    hora: "16:00",
    sede: "San Francisco",
    local: "Qatar",
    visita: "Suiza",
  },
  {
    id: "B3",
    fase: "grupos",
    grupo: "B",
    fechaISO: "2026-06-18T19:00:00Z",
    fecha: "18 Jun",
    hora: "16:00",
    sede: "Los Ángeles",
    local: "Suiza",
    visita: "Bosnia",
  },
  {
    id: "B4",
    fase: "grupos",
    grupo: "B",
    fechaISO: "2026-06-18T22:00:00Z",
    fecha: "18 Jun",
    hora: "19:00",
    sede: "Vancouver",
    local: "Canadá",
    visita: "Qatar",
  },
  {
    id: "B5",
    fase: "grupos",
    grupo: "B",
    fechaISO: "2026-06-24T19:00:00Z",
    fecha: "24 Jun",
    hora: "16:00",
    sede: "Vancouver",
    local: "Suiza",
    visita: "Canadá",
  },
  {
    id: "B6",
    fase: "grupos",
    grupo: "B",
    fechaISO: "2026-06-24T19:00:00Z",
    fecha: "24 Jun",
    hora: "16:00",
    sede: "Kansas City",
    local: "Bosnia",
    visita: "Qatar",
  },
  // ── GRUPO C ──
  {
    id: "C1",
    fase: "grupos",
    grupo: "C",
    fechaISO: "2026-06-13T22:00:00Z",
    fecha: "13 Jun",
    hora: "19:00",
    sede: "Nueva Jersey",
    local: "Brasil",
    visita: "Marruecos",
  },
  {
    id: "C2",
    fase: "grupos",
    grupo: "C",
    fechaISO: "2026-06-14T01:00:00Z",
    fecha: "13 Jun",
    hora: "22:00",
    sede: "Boston",
    local: "Haití",
    visita: "Escocia",
  },
  {
    id: "C3",
    fase: "grupos",
    grupo: "C",
    fechaISO: "2026-06-19T22:00:00Z",
    fecha: "19 Jun",
    hora: "19:00",
    sede: "Boston",
    local: "Escocia",
    visita: "Marruecos",
  },
  {
    id: "C4",
    fase: "grupos",
    grupo: "C",
    fechaISO: "2026-06-20T00:30:00Z",
    fecha: "19 Jun",
    hora: "21:30",
    sede: "Philadelphia",
    local: "Brasil",
    visita: "Haití",
  },
  {
    id: "C5",
    fase: "grupos",
    grupo: "C",
    fechaISO: "2026-06-24T22:00:00Z",
    fecha: "25 Jun",
    hora: "20:00",
    sede: "Atlanta",
    local: "Marruecos",
    visita: "Haití",
  },
  {
    id: "C6",
    fase: "grupos",
    grupo: "C",
    fechaISO: "2026-06-24T22:00:00Z",
    fecha: "25 Jun",
    hora: "20:00",
    sede: "Nueva Jersey",
    local: "Escocia",
    visita: "Brasil",
  },
  // ── GRUPO D ──
  {
    id: "D1",
    fase: "grupos",
    grupo: "D",
    fechaISO: "2026-06-14T04:00:00Z",
    fecha: "14 Jun",
    hora: "01:00",
    sede: "Vancouver",
    local: "Australia",
    visita: "Turquía",
  },
  {
    id: "D2",
    fase: "grupos",
    grupo: "D",
    fechaISO: "2026-06-13T01:00:00Z",
    fecha: "12 Jun",
    hora: "22:00",
    sede: "Los Ángeles",
    local: "Estados Unidos",
    visita: "Paraguay",
  },
  {
    id: "D3",
    fase: "grupos",
    grupo: "D",
    fechaISO: "2026-06-19T19:00:00Z",
    fecha: "19 Jun",
    hora: "16:00",
    sede: "Seattle",
    local: "Estados Unidos",
    visita: "Australia",
  },
  {
    id: "D4",
    fase: "grupos",
    grupo: "D",
    fechaISO: "2026-06-20T03:00:00Z",
    fecha: "19 Jun",
    hora: "00:00",
    sede: "San Francisco",
    local: "Turquía",
    visita: "Paraguay",
  },
  {
    id: "D5",
    fase: "grupos",
    grupo: "D",
    fechaISO: "2026-06-26T01:00:00Z",
    fecha: "25 Jun",
    hora: "23:00",
    sede: "Seattle",
    local: "Turquía",
    visita: "Estados Unidos",
  },
  {
    id: "D6",
    fase: "grupos",
    grupo: "D",
    fechaISO: "2026-06-26T01:00:00Z",
    fecha: "25 Jun",
    hora: "23:00",
    sede: "Dallas",
    local: "Paraguay",
    visita: "Australia",
  },
  // ── GRUPO E ──
  {
    id: "E1",
    fase: "grupos",
    grupo: "E",
    fechaISO: "2026-06-14T17:00:00Z",
    fecha: "14 Jun",
    hora: "14:00",
    sede: "Houston",
    local: "Alemania",
    visita: "Curazao",
  },
  {
    id: "E2",
    fase: "grupos",
    grupo: "E",
    fechaISO: "2026-06-14T23:00:00Z",
    fecha: "14 Jun",
    hora: "20:00",
    sede: "Philadelphia",
    local: "Costa de Marfil",
    visita: "Ecuador",
  },
  {
    id: "E3",
    fase: "grupos",
    grupo: "E",
    fechaISO: "2026-06-20T20:00:00Z",
    fecha: "20 Jun",
    hora: "17:00",
    sede: "Toronto",
    local: "Alemania",
    visita: "Costa de Marfil",
  },
  {
    id: "E4",
    fase: "grupos",
    grupo: "E",
    fechaISO: "2026-06-21T00:00:00Z",
    fecha: "20 Jun",
    hora: "21:00",
    sede: "Kansas City",
    local: "Ecuador",
    visita: "Curazao",
  },
  {
    id: "E5",
    fase: "grupos",
    grupo: "E",
    fechaISO: "2026-06-25T20:00:00Z",
    fecha: "26 Jun",
    hora: "17:00",
    sede: "Toronto",
    local: "Curazao",
    visita: "Costa de Marfil",
  },
  {
    id: "E6",
    fase: "grupos",
    grupo: "E",
    fechaISO: "2026-06-25T20:00:00Z",
    fecha: "26 Jun",
    hora: "17:00",
    sede: "Philadelphia",
    local: "Ecuador",
    visita: "Alemania",
  },
  // ── GRUPO F ──
  {
    id: "F1",
    fase: "grupos",
    grupo: "F",
    fechaISO: "2026-06-14T20:00:00Z",
    fecha: "14 Jun",
    hora: "17:00",
    sede: "Dallas",
    local: "Países Bajos",
    visita: "Japón",
  },
  {
    id: "F2",
    fase: "grupos",
    grupo: "F",
    fechaISO: "2026-06-15T02:00:00Z",
    fecha: "14 Jun",
    hora: "23:00",
    sede: "Monterrey",
    local: "Suecia",
    visita: "Túnez",
  },
  {
    id: "F3",
    fase: "grupos",
    grupo: "F",
    fechaISO: "2026-06-20T17:00:00Z",
    fecha: "20 Jun",
    hora: "14:00",
    sede: "Houston",
    local: "Países Bajos",
    visita: "Suecia",
  },
  {
    id: "F4",
    fase: "grupos",
    grupo: "F",
    fechaISO: "2026-06-21T04:00:00Z",
    fecha: "20 Jun",
    hora: "01:00",
    sede: "Monterrey",
    local: "Túnez",
    visita: "Japón",
  },
  {
    id: "F5",
    fase: "grupos",
    grupo: "F",
    fechaISO: "2026-06-25T23:00:00Z",
    fecha: "26 Jun",
    hora: "20:00",
    sede: "Dallas",
    local: "Túnez",
    visita: "Países Bajos",
  },
  {
    id: "F6",
    fase: "grupos",
    grupo: "F",
    fechaISO: "2026-06-25T23:00:00Z",
    fecha: "26 Jun",
    hora: "20:00",
    sede: "Houston",
    local: "Japón",
    visita: "Suecia",
  },
  // ── GRUPO G ──
  {
    id: "G1",
    fase: "grupos",
    grupo: "G",
    fechaISO: "2026-06-15T19:00:00Z",
    fecha: "15 Jun",
    hora: "16:00",
    sede: "Seattle",
    local: "Bélgica",
    visita: "Egipto",
  },
  {
    id: "G2",
    fase: "grupos",
    grupo: "G",
    fechaISO: "2026-06-16T01:00:00Z",
    fecha: "15 Jun",
    hora: "22:00",
    sede: "Los Ángeles",
    local: "Irán",
    visita: "Nueva Zelanda",
  },
  {
    id: "G3",
    fase: "grupos",
    grupo: "G",
    fechaISO: "2026-06-21T19:00:00Z",
    fecha: "21 Jun",
    hora: "16:00",
    sede: "Los Ángeles",
    local: "Bélgica",
    visita: "Irán",
  },
  {
    id: "G4",
    fase: "grupos",
    grupo: "G",
    fechaISO: "2026-06-22T01:00:00Z",
    fecha: "21 Jun",
    hora: "22:00",
    sede: "Vancouver",
    local: "Nueva Zelanda",
    visita: "Egipto",
  },
  {
    id: "G5",
    fase: "grupos",
    grupo: "G",
    fechaISO: "2026-06-27T03:00:00Z",
    fecha: "27 Jun",
    hora: "00:00",
    sede: "Seattle",
    local: "Nueva Zelanda",
    visita: "Bélgica",
  },
  {
    id: "G6",
    fase: "grupos",
    grupo: "G",
    fechaISO: "2026-06-27T03:00:00Z",
    fecha: "27 Jun",
    hora: "00:00",
    sede: "Los Ángeles",
    local: "Egipto",
    visita: "Irán",
  },
  // ── GRUPO H ──
  {
    id: "H1",
    fase: "grupos",
    grupo: "H",
    fechaISO: "2026-06-15T16:00:00Z",
    fecha: "15 Jun",
    hora: "13:00",
    sede: "Atlanta",
    local: "España",
    visita: "Cabo Verde",
  },
  {
    id: "H2",
    fase: "grupos",
    grupo: "H",
    fechaISO: "2026-06-15T22:00:00Z",
    fecha: "15 Jun",
    hora: "19:00",
    sede: "Miami",
    local: "Arabia Saudita",
    visita: "Uruguay",
  },
  {
    id: "H3",
    fase: "grupos",
    grupo: "H",
    fechaISO: "2026-06-21T16:00:00Z",
    fecha: "21 Jun",
    hora: "13:00",
    sede: "Atlanta",
    local: "España",
    visita: "Arabia Saudita",
  },
  {
    id: "H4",
    fase: "grupos",
    grupo: "H",
    fechaISO: "2026-06-21T22:00:00Z",
    fecha: "21 Jun",
    hora: "19:00",
    sede: "Miami",
    local: "Uruguay",
    visita: "Cabo Verde",
  },
  {
    id: "H5",
    fase: "grupos",
    grupo: "H",
    fechaISO: "2026-06-26T00:00:00Z",
    fecha: "26 Jun",
    hora: "21:00",
    sede: "Miami",
    local: "Cabo Verde",
    visita: "Arabia Saudita",
  },
  {
    id: "H6",
    fase: "grupos",
    grupo: "H",
    fechaISO: "2026-06-26T00:00:00Z",
    fecha: "26 Jun",
    hora: "21:00",
    sede: "Atlanta",
    local: "Uruguay",
    visita: "España",
  },
  // ── GRUPO I ──
  {
    id: "I1",
    fase: "grupos",
    grupo: "I",
    fechaISO: "2026-06-16T19:00:00Z",
    fecha: "16 Jun",
    hora: "16:00",
    sede: "Nueva Jersey",
    local: "Francia",
    visita: "Senegal",
  },
  {
    id: "I2",
    fase: "grupos",
    grupo: "I",
    fechaISO: "2026-06-16T22:00:00Z",
    fecha: "16 Jun",
    hora: "19:00",
    sede: "Boston",
    local: "Irak",
    visita: "Noruega",
  },
  {
    id: "I3",
    fase: "grupos",
    grupo: "I",
    fechaISO: "2026-06-22T21:00:00Z",
    fecha: "22 Jun",
    hora: "18:00",
    sede: "Philadelphia",
    local: "Francia",
    visita: "Irak",
  },
  {
    id: "I4",
    fase: "grupos",
    grupo: "I",
    fechaISO: "2026-06-23T00:00:00Z",
    fecha: "22 Jun",
    hora: "21:00",
    sede: "Nueva Jersey",
    local: "Noruega",
    visita: "Senegal",
  },
  {
    id: "I5",
    fase: "grupos",
    grupo: "I",
    fechaISO: "2026-06-25T19:00:00Z",
    fecha: "26 Jun",
    hora: "16:00",
    sede: "Nueva Jersey",
    local: "Noruega",
    visita: "Francia",
  },
  {
    id: "I6",
    fase: "grupos",
    grupo: "I",
    fechaISO: "2026-06-25T19:00:00Z",
    fecha: "26 Jun",
    hora: "16:00",
    sede: "Boston",
    local: "Senegal",
    visita: "Irak",
  },
  // ── GRUPO J ──
  {
    id: "J1",
    fase: "grupos",
    grupo: "J",
    fechaISO: "2026-06-17T01:00:00Z",
    fecha: "16 Jun",
    hora: "22:00",
    sede: "Kansas City",
    local: "Argentina",
    visita: "Argelia",
  },
  {
    id: "J2",
    fase: "grupos",
    grupo: "J",
    fechaISO: "2026-06-17T04:00:00Z",
    fecha: "17 Jun",
    hora: "01:00",
    sede: "San Francisco",
    local: "Austria",
    visita: "Jordania",
  },
  {
    id: "J3",
    fase: "grupos",
    grupo: "J",
    fechaISO: "2026-06-22T17:00:00Z",
    fecha: "22 Jun",
    hora: "14:00",
    sede: "Dallas",
    local: "Argentina",
    visita: "Austria",
  },
  {
    id: "J4",
    fase: "grupos",
    grupo: "J",
    fechaISO: "2026-06-23T03:00:00Z",
    fecha: "22 Jun",
    hora: "00:00",
    sede: "San Francisco",
    local: "Jordania",
    visita: "Argelia",
  },
  {
    id: "J5",
    fase: "grupos",
    grupo: "J",
    fechaISO: "2026-06-27T02:00:00Z",
    fecha: "27 Jun",
    hora: "23:00",
    sede: "Kansas City",
    local: "Jordania",
    visita: "Argentina",
  },
  {
    id: "J6",
    fase: "grupos",
    grupo: "J",
    fechaISO: "2026-06-27T02:00:00Z",
    fecha: "27 Jun",
    hora: "23:00",
    sede: "Dallas",
    local: "Argelia",
    visita: "Austria",
  },
  // ── GRUPO K ──
  {
    id: "K1",
    fase: "grupos",
    grupo: "K",
    fechaISO: "2026-06-17T17:00:00Z",
    fecha: "17 Jun",
    hora: "14:00",
    sede: "Houston",
    local: "Portugal",
    visita: "RD del Congo",
  },
  {
    id: "K2",
    fase: "grupos",
    grupo: "K",
    fechaISO: "2026-06-18T02:00:00Z",
    fecha: "17 Jun",
    hora: "23:00",
    sede: "Ciudad de México",
    local: "Uzbekistán",
    visita: "Colombia",
  },
  {
    id: "K3",
    fase: "grupos",
    grupo: "K",
    fechaISO: "2026-06-23T17:00:00Z",
    fecha: "23 Jun",
    hora: "14:00",
    sede: "Houston",
    local: "Portugal",
    visita: "Uzbekistán",
  },
  {
    id: "K4",
    fase: "grupos",
    grupo: "K",
    fechaISO: "2026-06-24T02:00:00Z",
    fecha: "23 Jun",
    hora: "23:00",
    sede: "Guadalajara",
    local: "Colombia",
    visita: "RD del Congo",
  },
  {
    id: "K5",
    fase: "grupos",
    grupo: "K",
    fechaISO: "2026-06-27T01:30:00Z",
    fecha: "27 Jun",
    hora: "22:30",
    sede: "Houston",
    local: "Colombia",
    visita: "Portugal",
  },
  {
    id: "K6",
    fase: "grupos",
    grupo: "K",
    fechaISO: "2026-06-27T01:30:00Z",
    fecha: "27 Jun",
    hora: "22:30",
    sede: "Ciudad de México",
    local: "RD del Congo",
    visita: "Uzbekistán",
  },
  // ── GRUPO L ──
  {
    id: "L1",
    fase: "grupos",
    grupo: "L",
    fechaISO: "2026-06-17T20:00:00Z",
    fecha: "17 Jun",
    hora: "17:00",
    sede: "Dallas",
    local: "Inglaterra",
    visita: "Croacia",
  },
  {
    id: "L2",
    fase: "grupos",
    grupo: "L",
    fechaISO: "2026-06-17T23:00:00Z",
    fecha: "17 Jun",
    hora: "20:00",
    sede: "Toronto",
    local: "Ghana",
    visita: "Panamá",
  },
  {
    id: "L3",
    fase: "grupos",
    grupo: "L",
    fechaISO: "2026-06-23T20:00:00Z",
    fecha: "23 Jun",
    hora: "17:00",
    sede: "Boston",
    local: "Inglaterra",
    visita: "Ghana",
  },
  {
    id: "L4",
    fase: "grupos",
    grupo: "L",
    fechaISO: "2026-06-23T23:00:00Z",
    fecha: "23 Jun",
    hora: "20:00",
    sede: "Toronto",
    local: "Panamá",
    visita: "Croacia",
  },
  {
    id: "L5",
    fase: "grupos",
    grupo: "L",
    fechaISO: "2026-06-26T19:00:00Z",
    fecha: "27 Jun",
    hora: "16:00",
    sede: "Dallas",
    local: "Panamá",
    visita: "Inglaterra",
  },
  {
    id: "L6",
    fase: "grupos",
    grupo: "L",
    fechaISO: "2026-06-26T19:00:00Z",
    fecha: "27 Jun",
    hora: "16:00",
    sede: "Boston",
    local: "Croacia",
    visita: "Ghana",
  },
  // ── 1/16 ──
  {
    id: "R1",
    fase: "1/16",
    fechaISO: "2026-07-04T22:00:00Z",
    fecha: "4 Jul",
    hora: "19:00",
    sede: "Dallas",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R2",
    fase: "1/16",
    fechaISO: "2026-07-05T01:00:00Z",
    fecha: "4 Jul",
    hora: "22:00",
    sede: "Los Ángeles",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R3",
    fase: "1/16",
    fechaISO: "2026-07-05T22:00:00Z",
    fecha: "5 Jul",
    hora: "19:00",
    sede: "Nueva York",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R4",
    fase: "1/16",
    fechaISO: "2026-07-06T01:00:00Z",
    fecha: "5 Jul",
    hora: "22:00",
    sede: "Miami",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R5",
    fase: "1/16",
    fechaISO: "2026-07-06T22:00:00Z",
    fecha: "6 Jul",
    hora: "19:00",
    sede: "Houston",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R6",
    fase: "1/16",
    fechaISO: "2026-07-07T01:00:00Z",
    fecha: "6 Jul",
    hora: "22:00",
    sede: "Seattle",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R7",
    fase: "1/16",
    fechaISO: "2026-07-07T22:00:00Z",
    fecha: "7 Jul",
    hora: "19:00",
    sede: "Boston",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R8",
    fase: "1/16",
    fechaISO: "2026-07-08T01:00:00Z",
    fecha: "7 Jul",
    hora: "22:00",
    sede: "Atlanta",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R9",
    fase: "1/16",
    fechaISO: "2026-07-08T22:00:00Z",
    fecha: "8 Jul",
    hora: "19:00",
    sede: "Kansas City",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R10",
    fase: "1/16",
    fechaISO: "2026-07-09T01:00:00Z",
    fecha: "8 Jul",
    hora: "22:00",
    sede: "San Francisco",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R11",
    fase: "1/16",
    fechaISO: "2026-07-09T22:00:00Z",
    fecha: "9 Jul",
    hora: "19:00",
    sede: "Toronto",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R12",
    fase: "1/16",
    fechaISO: "2026-07-10T01:00:00Z",
    fecha: "9 Jul",
    hora: "22:00",
    sede: "Ciudad de México",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R13",
    fase: "1/16",
    fechaISO: "2026-07-10T22:00:00Z",
    fecha: "10 Jul",
    hora: "19:00",
    sede: "Guadalajara",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R14",
    fase: "1/16",
    fechaISO: "2026-07-11T01:00:00Z",
    fecha: "10 Jul",
    hora: "22:00",
    sede: "Nueva York",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R15",
    fase: "1/16",
    fechaISO: "2026-07-11T22:00:00Z",
    fecha: "11 Jul",
    hora: "19:00",
    sede: "Dallas",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "R16",
    fase: "1/16",
    fechaISO: "2026-07-12T01:00:00Z",
    fecha: "11 Jul",
    hora: "22:00",
    sede: "Los Ángeles",
    local: "TBD",
    visita: "TBD",
  },
  // ── OCTAVOS ──
  {
    id: "O1",
    fase: "octavos",
    fechaISO: "2026-07-14T22:00:00Z",
    fecha: "14 Jul",
    hora: "19:00",
    sede: "Nueva York",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "O2",
    fase: "octavos",
    fechaISO: "2026-07-15T01:00:00Z",
    fecha: "14 Jul",
    hora: "22:00",
    sede: "Houston",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "O3",
    fase: "octavos",
    fechaISO: "2026-07-15T22:00:00Z",
    fecha: "15 Jul",
    hora: "19:00",
    sede: "Miami",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "O4",
    fase: "octavos",
    fechaISO: "2026-07-16T01:00:00Z",
    fecha: "15 Jul",
    hora: "22:00",
    sede: "Seattle",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "O5",
    fase: "octavos",
    fechaISO: "2026-07-16T22:00:00Z",
    fecha: "16 Jul",
    hora: "19:00",
    sede: "Dallas",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "O6",
    fase: "octavos",
    fechaISO: "2026-07-17T01:00:00Z",
    fecha: "16 Jul",
    hora: "22:00",
    sede: "Los Ángeles",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "O7",
    fase: "octavos",
    fechaISO: "2026-07-17T22:00:00Z",
    fecha: "17 Jul",
    hora: "19:00",
    sede: "Boston",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "O8",
    fase: "octavos",
    fechaISO: "2026-07-18T01:00:00Z",
    fecha: "17 Jul",
    hora: "22:00",
    sede: "Atlanta",
    local: "TBD",
    visita: "TBD",
  },
  // ── CUARTOS ──
  {
    id: "Q1",
    fase: "cuartos",
    fechaISO: "2026-07-21T22:00:00Z",
    fecha: "21 Jul",
    hora: "19:00",
    sede: "Nueva York",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "Q2",
    fase: "cuartos",
    fechaISO: "2026-07-22T01:00:00Z",
    fecha: "21 Jul",
    hora: "22:00",
    sede: "Los Ángeles",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "Q3",
    fase: "cuartos",
    fechaISO: "2026-07-22T22:00:00Z",
    fecha: "22 Jul",
    hora: "19:00",
    sede: "Dallas",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "Q4",
    fase: "cuartos",
    fechaISO: "2026-07-23T01:00:00Z",
    fecha: "22 Jul",
    hora: "22:00",
    sede: "Miami",
    local: "TBD",
    visita: "TBD",
  },
  // ── SEMIS ──
  {
    id: "S1",
    fase: "semis",
    fechaISO: "2026-07-26T22:00:00Z",
    fecha: "26 Jul",
    hora: "19:00",
    sede: "Dallas",
    local: "TBD",
    visita: "TBD",
  },
  {
    id: "S2",
    fase: "semis",
    fechaISO: "2026-07-27T22:00:00Z",
    fecha: "27 Jul",
    hora: "19:00",
    sede: "Nueva York",
    local: "TBD",
    visita: "TBD",
  },
  // ── 3ER PUESTO ──
  {
    id: "TP",
    fase: "3er_puesto",
    fechaISO: "2026-07-19T22:00:00Z",
    fecha: "19 Jul",
    hora: "19:00",
    sede: "Miami",
    local: "TBD",
    visita: "TBD",
  },
  // ── FINAL ──
  {
    id: "F",
    fase: "final",
    fechaISO: "2026-07-20T01:00:00Z",
    fecha: "19 Jul",
    hora: "22:00",
    sede: "Nueva York",
    local: "TBD",
    visita: "TBD",
  },
];

export const GRUPOS_LIST = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
];

export const FASES_LABEL: Record<Fase, string> = {
  grupos: "Fase de Grupos",
  "1/16": "Dieciseisavos",
  octavos: "Octavos de Final",
  cuartos: "Cuartos de Final",
  semis: "Semifinales",
  "3er_puesto": "Tercer Puesto",
  final: "Final",
};
